language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="https://github.com/django/django/zipball/master"
  - DJANGO="django==1.5 --use-mirrors"
  - DJANGO="django==1.4 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install mockup
  - export PYTHONPATH=.

script:
  - python chimps/runtests/runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.4 --use-mirrors"
