language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO="django==1.6 --use-mirrors"
  - DJANGO="django==1.5.5 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install mock mailsnake --use-mirrors
  - export PYTHONPATH=.

script:
  - python chimps/runtests/runtests.py
